"use client";

import { useMemo, useState } from "react";
import Link from "next/link";

type Assignment = { id:number; name:string; role:string; budget:number; spent:number; status:string; scope:string };
type Expense = { id:number; volunteer:string; amount:number; purpose:string; place:string; date:string; status:string; note:string };
const money=(value:number)=>new Intl.NumberFormat("en-BD",{style:"currency",currency:"BDT",maximumFractionDigits:0}).format(value);
const initialAssignments:Assignment[]=[{id:1,name:"Amina Rahman",role:"Relief distribution lead",budget:80000,spent:24500,status:"ACTIVE",scope:"Coordinate food parcels and maintain beneficiary handover records."},{id:2,name:"Rafiul Islam",role:"Medical supplies coordinator",budget:50000,spent:12000,status:"ACTIVE",scope:"Source approved medicine and deliver through registered clinics."}];
const initialExpenses:Expense[]=[{id:1,volunteer:"Amina Rahman",amount:24500,purpose:"Food parcel supplies",place:"Sunamganj Sadar",date:"24 Sep 2026",status:"PAID",note:"Invoice verified by finance admin."},{id:2,volunteer:"Rafiul Islam",amount:12000,purpose:"Essential medicine",place:"Derai clinic",date:"23 Sep 2026",status:"PAID",note:"Clinic handover record verified."},{id:3,volunteer:"Amina Rahman",amount:8500,purpose:"Water purification tablets",place:"Jamalganj",date:"25 Sep 2026",status:"PENDING_REVIEW",note:"Awaiting finance review."}];

export default function VolunteerAssignmentsPage(){
 const [assignments,setAssignments]=useState(initialAssignments); const [expenses,setExpenses]=useState(initialExpenses); const [view,setView]=useState<"overview"|"admin"|"volunteer">("overview"); const [selected,setSelected]=useState(1); const [message,setMessage]=useState("");
 const totalBudget=assignments.reduce((sum,a)=>sum+a.budget,0), totalSpent=assignments.reduce((sum,a)=>sum+a.spent,0); const active=assignments.find(a=>a.id===selected)!; const remaining=active.budget-active.spent;
 const approve=(id:number)=>{const entry=expenses.find(e=>e.id===id)!;setExpenses(expenses.map(e=>e.id===id?{...e,status:"PAID",note:"Invoice and purpose approved by finance admin."}:e));setAssignments(assignments.map(a=>a.name===entry.volunteer?{...a,spent:a.spent+entry.amount}:a));setMessage("Expense approved and recorded in the immutable campaign ledger.");};
 const submit=(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);const amount=Number(form.get("amount"));if(amount<=0||amount>remaining){setMessage(`Amount must be within the remaining ${money(remaining)} budget.`);return;}setExpenses([{id:Date.now(),volunteer:active.name,amount,purpose:String(form.get("purpose")),place:String(form.get("place")),date:new Date().toLocaleDateString("en-GB",{day:"numeric",month:"short",year:"numeric"}),status:"PENDING_REVIEW",note:"Awaiting finance review."},...expenses]);setMessage("Expense request submitted. It cannot be paid or counted as spent until admin review.");event.currentTarget.reset();};
 const rows=useMemo(()=>expenses,[expenses]);
 return <main className="min-h-screen bg-slate-50"><header className="border-b bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4"><Link href="/" className="font-bold text-emerald-700">EcoKnot</Link><span className="text-sm text-slate-500">Fund security & volunteer accountability</span></div></header><section className="mx-auto max-w-7xl px-6 py-10"><div className="rounded-3xl bg-gradient-to-br from-emerald-800 to-teal-700 p-8 text-white"><p className="text-sm font-bold tracking-wider text-emerald-100">CAMPAIGN OPERATIONS</p><h1 className="mt-2 text-3xl font-bold md:text-4xl">Assign volunteers. Protect every taka.</h1><p className="mt-3 max-w-3xl text-emerald-50">Every use of campaign money needs a named responsibility, a capped budget, proof of purpose, and finance approval before payment.</p></div><div className="mt-6 flex flex-wrap gap-2">{(["overview","admin","volunteer"] as const).map(tab=><button key={tab} onClick={()=>setView(tab)} className={`rounded-xl px-4 py-2 text-sm font-bold ${view===tab?"bg-emerald-700 text-white":"bg-white text-slate-600 ring-1 ring-slate-200"}`}>{tab==="overview"?"Transparency ledger":tab==="admin"?"Admin controls":"Volunteer workspace"}</button>)}</div>{message&&<div className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800">{message}</div>}
 {view==="overview"&&<><div className="mt-7 grid gap-4 md:grid-cols-3"><Stat label="Approved volunteer budget" value={money(totalBudget)}/><Stat label="Verified funds distributed" value={money(totalSpent)}/><Stat label="Funds still protected" value={money(totalBudget-totalSpent)}/></div><div className="mt-7 rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h2 className="text-xl font-bold">Public distribution ledger</h2><p className="mt-1 text-sm text-slate-500">Amounts become part of the spent total only after finance review and payment.</p><div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b text-slate-500"><tr><th className="pb-3">Volunteer</th><th className="pb-3">Use & location</th><th className="pb-3">Amount</th><th className="pb-3">Status</th></tr></thead><tbody>{rows.map(item=><tr key={item.id} className="border-b last:border-0"><td className="py-4 font-semibold">{item.volunteer}<div className="font-normal text-slate-500">{item.date}</div></td><td className="py-4">{item.purpose}<div className="text-slate-500">{item.place}</div></td><td className="py-4 font-bold">{money(item.amount)}</td><td className="py-4"><span className={`rounded-full px-3 py-1 text-xs font-bold ${item.status==="PAID"?"bg-emerald-100 text-emerald-700":"bg-amber-100 text-amber-700"}`}>{item.status.replace("_"," ")}</span></td></tr>)}</tbody></table></div></div></>}
 {view==="admin"&&<div className="mt-7 grid gap-6 lg:grid-cols-[1fr_1.2fr]"><div className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h2 className="text-xl font-bold">Volunteer assignments</h2><p className="mt-1 text-sm text-slate-500">Budget caps are set by finance—not the volunteer.</p><div className="mt-5 space-y-4">{assignments.map(a=><div key={a.id} className="rounded-xl border p-4"><div className="flex justify-between gap-3"><div><b>{a.name}</b><p className="text-sm text-emerald-700">{a.role}</p></div><span className="text-xs font-bold text-emerald-700">{a.status}</span></div><p className="mt-2 text-sm text-slate-600">{a.scope}</p><div className="mt-3 flex justify-between text-sm"><span>{money(a.spent)} spent</span><b>{money(a.budget-a.spent)} remaining</b></div></div>)}</div></div><div className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h2 className="text-xl font-bold">Expenses awaiting approval</h2><div className="mt-5 space-y-4">{expenses.filter(e=>e.status==="PENDING_REVIEW").map(e=><div key={e.id} className="rounded-xl border border-amber-200 bg-amber-50 p-4"><div className="flex flex-wrap justify-between gap-3"><div><b>{e.purpose} · {money(e.amount)}</b><p className="text-sm text-slate-600">{e.volunteer} — {e.place}</p><p className="mt-1 text-xs text-slate-500">{e.note}</p></div><button onClick={()=>approve(e.id)} className="h-fit rounded-lg bg-emerald-700 px-4 py-2 text-sm font-bold text-white">Approve & mark paid</button></div></div>)}{!expenses.some(e=>e.status==="PENDING_REVIEW")&&<p className="text-slate-500">Nothing waiting for review.</p>}</div></div></div>}
 {view==="volunteer"&&<div className="mt-7 grid gap-6 lg:grid-cols-[0.75fr_1.25fr]"><div className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h2 className="text-xl font-bold">My assignment</h2><select value={selected} onChange={e=>setSelected(Number(e.target.value))} className="mt-5 w-full rounded-xl border p-3">{assignments.map(a=><option key={a.id} value={a.id}>{a.name} — {a.role}</option>)}</select><p className="mt-5 text-sm text-slate-600">Approved ceiling</p><p className="text-2xl font-bold">{money(active.budget)}</p><p className="mt-4 text-sm text-slate-600">Available to request</p><p className="text-2xl font-bold text-emerald-700">{money(remaining)}</p><p className="mt-5 text-sm leading-6 text-slate-600">A volunteer cannot transfer funds or change this limit. Each request requires a purpose, place, and evidence link.</p></div><form onSubmit={submit} className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h2 className="text-xl font-bold">Submit a distribution expense</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><input required name="purpose" placeholder="What was purchased or distributed?" className="rounded-xl border p-3 md:col-span-2"/><input required name="place" placeholder="Where was it used?" className="rounded-xl border p-3"/><input required min="1" type="number" name="amount" placeholder="Amount in BDT" className="rounded-xl border p-3"/><input name="evidence" placeholder="Receipt / evidence URL (optional)" className="rounded-xl border p-3 md:col-span-2"/></div><button className="mt-5 rounded-xl bg-emerald-700 px-5 py-3 font-bold text-white">Submit for finance review</button></form></div>}</section></main>;
}
function Stat({label,value}:{label:string;value:string}){return <div className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-2xl font-bold text-slate-900">{value}</p></div>}
