"use client";
import { useEffect, useState } from "react";
import { categoryLabels, currency, Fund, getFunds, saveFunds } from "@/lib/fundraising";

export default function FundraisingAdmin(){
 const [funds,setFunds]=useState<Fund[]>([]); const [allowed,setAllowed]=useState(false);
 useEffect(()=>{const u=JSON.parse(localStorage.getItem("user")||"null");setAllowed(u?.role==="ADMIN");setFunds(getFunds())},[]);
 const decide=(id:string,status:"APPROVED"|"REJECTED")=>{const updated=funds.map(f=>f.id===id?{...f,status}:f);setFunds(updated);saveFunds(updated)};
 if(!allowed)return <main className="min-h-screen bg-slate-50"><div className="mx-auto max-w-3xl p-10"><h1 className="text-2xl font-bold">Administrator access required</h1><p className="mt-2 text-slate-600">Only accounts with the ADMIN role can approve or reject fundraising campaigns.</p></div></main>;
 return <main className="min-h-screen bg-slate-50"><section className="mx-auto max-w-6xl px-6 py-10"><h1 className="text-3xl font-bold">Fundraising review</h1><p className="mt-2 text-slate-600">Review submitted campaigns before they become publicly visible.</p><div className="mt-7 space-y-4">{funds.filter(f=>f.status==="PENDING_REVIEW").map(f=><article key={f.id} className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><div className="flex flex-wrap justify-between gap-4"><div><p className="text-sm font-bold text-emerald-700">{categoryLabels[f.category]} · {currency(f.goalAmount)}</p><h2 className="mt-1 text-xl font-bold">{f.title}</h2><p className="mt-2 text-sm text-slate-600">Beneficiary: {f.beneficiary} · {f.location} · {f.contact}</p><p className="mt-3 max-w-3xl text-slate-700">{f.description}</p></div><div className="flex h-fit gap-2"><button onClick={()=>decide(f.id,"REJECTED")} className="rounded-xl border border-red-200 px-4 py-2 font-bold text-red-700">Reject</button><button onClick={()=>decide(f.id,"APPROVED")} className="rounded-xl bg-emerald-700 px-4 py-2 font-bold text-white">Approve</button></div></div></article>)}{funds.every(f=>f.status!=="PENDING_REVIEW")&&<div className="rounded-2xl bg-white p-10 text-center text-slate-500">No campaigns awaiting review.</div>}</div></section></main>;
}
