"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";

import { Fund, categoryLabels, saveFunds, getFunds } from "@/lib/fundraising";

export default function CreateFundraiser() {
 const router = useRouter(); const [saving, setSaving] = useState(false); const [form, setForm] = useState({ title:"", category:"MEDICAL", description:"", location:"", beneficiary:"", contact:"", goalAmount:"" });
 const change = (e: React.ChangeEvent<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>) => setForm({...form, [e.target.name]: e.target.value});
 const submit = (e: React.FormEvent) => { e.preventDefault(); const user = JSON.parse(localStorage.getItem("user") || "null"); if (!user) return router.push("/login"); setSaving(true); const fund: Fund = { id: crypto.randomUUID(), ...form, category: form.category as Fund["category"], goalAmount:Number(form.goalAmount), raisedAmount:0, status:"PENDING_REVIEW", authorId:user.id, author:user.name, createdAt:new Date().toISOString(), reactions:0, reactedBy:[], comments:[], contributions:[] }; saveFunds([fund, ...getFunds()]); router.push("/fundraising/my-campaigns"); };
 return <main className="min-h-screen bg-slate-50"><form onSubmit={submit} className="mx-auto max-w-3xl px-6 py-10"><div className="rounded-3xl bg-white p-7 shadow-sm ring-1 ring-slate-200"><h1 className="text-3xl font-bold">Start a fundraiser</h1><p className="mt-2 text-slate-600">Campaigns are reviewed before they are published. Share only accurate, consented information.</p><div className="mt-7 grid gap-5 md:grid-cols-2"><input required name="title" value={form.title} onChange={change} placeholder="Campaign title" className="rounded-xl border p-3 md:col-span-2"/><select name="category" value={form.category} onChange={change} className="rounded-xl border p-3">{Object.entries(categoryLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><input required name="goalAmount" type="number" min="1" value={form.goalAmount} onChange={change} placeholder="Target amount (BDT)" className="rounded-xl border p-3"/><input required name="beneficiary" value={form.beneficiary} onChange={change} placeholder="Beneficiary name" className="rounded-xl border p-3"/><input required name="location" value={form.location} onChange={change} placeholder="Location" className="rounded-xl border p-3"/><input required name="contact" value={form.contact} onChange={change} placeholder="Contact number" className="rounded-xl border p-3 md:col-span-2"/><textarea required name="description" value={form.description} onChange={change} rows={6} placeholder="Explain the need, use of funds, and relevant verification details" className="rounded-xl border p-3 md:col-span-2"/></div><button disabled={saving} className="mt-7 w-full rounded-xl bg-emerald-700 py-3 font-bold text-white disabled:opacity-50">{saving ? "Submitting…" : "Submit for review"}</button></div></form></main>;
}
