package backend.service;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import backend.entity.*;
import backend.exception.ResourceNotFoundException;
import backend.repository.*;

@Service @Transactional
public class FundraisingService {
 private final FundCampaignRepository campaigns; private final FundCommentRepository comments; private final FundReactionRepository reactions; private final FundContributionRepository contributions; private final UserRepository users;
 public FundraisingService(FundCampaignRepository campaigns, FundCommentRepository comments, FundReactionRepository reactions, FundContributionRepository contributions, UserRepository users){this.campaigns=campaigns;this.comments=comments;this.reactions=reactions;this.contributions=contributions;this.users=users;}
 private User user(Long id){return users.findById(id).orElseThrow(()->new ResourceNotFoundException("User not found"));} private FundCampaign campaign(Long id){return campaigns.findById(id).orElseThrow(()->new ResourceNotFoundException("Campaign not found"));}
 private void admin(Long id){if(!"ADMIN".equalsIgnoreCase(user(id).getRole()))throw new RuntimeException("Administrator access required");}
 public Map<String,Object> create(Long userId, FundCampaign payload){User author=user(userId); if(payload.getGoalAmount()==null||payload.getGoalAmount().signum()<=0)throw new RuntimeException("A positive target amount is required"); payload.setAuthor(author);payload.setRaisedAmount(BigDecimal.ZERO);payload.setStatus(FundStatus.PENDING_REVIEW);return campaignView(campaigns.save(payload));}
 @Transactional(readOnly=true) public List<Map<String,Object>> approved(){return campaigns.findByStatusOrderByCreatedAtDesc(FundStatus.APPROVED).stream().map(this::campaignView).toList();}
 @Transactional(readOnly=true) public Map<String,Object> details(Long id){return campaignView(campaign(id));}
 @Transactional(readOnly=true) public List<Map<String,Object>> mine(Long userId){return campaigns.findByAuthorIdOrderByCreatedAtDesc(userId).stream().map(this::campaignView).toList();}
 @Transactional(readOnly=true) public List<Map<String,Object>> pending(Long adminId){admin(adminId);return campaigns.findByStatusOrderByCreatedAtDesc(FundStatus.PENDING_REVIEW).stream().map(this::campaignView).toList();}
 public Map<String,Object> review(Long id,Long adminId,FundStatus status,String note){admin(adminId);if(status!=FundStatus.APPROVED&&status!=FundStatus.REJECTED)throw new RuntimeException("Campaigns can only be approved or rejected during review");FundCampaign c=campaign(id);if(c.getStatus()!=FundStatus.PENDING_REVIEW)throw new RuntimeException("Campaign has already been reviewed");c.setStatus(status);c.setReviewNote(note);c.setReviewedBy(user(adminId));c.setReviewedAt(LocalDateTime.now());return campaignView(campaigns.save(c));}
 public Map<String,Object> close(Long id,Long userId){FundCampaign c=campaign(id);if(!c.getAuthor().getId().equals(userId))throw new RuntimeException("Only the campaign author can close it");c.setStatus(FundStatus.CLOSED);return campaignView(campaigns.save(c));}
 public Map<String,Object> toggleReaction(Long campaignId,Long userId){FundCampaign c=campaign(campaignId);User u=user(userId);Optional<FundReaction> existing=reactions.findByCampaignIdAndUserId(campaignId,userId);boolean reacted;if(existing.isPresent()){reactions.delete(existing.get());reacted=false;}else{FundReaction r=new FundReaction();r.setCampaign(c);r.setUser(u);reactions.save(r);reacted=true;}return Map.of("reacted",reacted,"reactionCount",reactions.countByCampaignId(campaignId));}
 public Map<String,Object> comment(Long campaignId,Long userId,String body,Long replyToId){if(body==null||body.isBlank())throw new RuntimeException("Comment cannot be empty");FundCampaign c=campaign(campaignId);FundComment comment=new FundComment();comment.setCampaign(c);comment.setAuthor(user(userId));comment.setBody(body.trim());if(replyToId!=null){FundComment parent=comments.findById(replyToId).orElseThrow(()->new ResourceNotFoundException("Parent comment not found"));if(!parent.getCampaign().getId().equals(campaignId))throw new RuntimeException("Reply must belong to this campaign");if(!c.getAuthor().getId().equals(userId))throw new RuntimeException("Only the campaign author can reply to comments");comment.setReplyTo(parent);}return commentView(comments.save(comment));}
 public Map<String,Object> createContribution(Long campaignId,Long donorId,BigDecimal amount,String method,String reference){FundCampaign c=campaign(campaignId);if(c.getStatus()!=FundStatus.APPROVED)throw new RuntimeException("Contributions are only accepted for approved campaigns");if(amount==null||amount.signum()<=0||method==null||method.isBlank()||reference==null||reference.isBlank())throw new RuntimeException("Amount, payment method, and payment reference are required");FundContribution item=new FundContribution();item.setCampaign(c);item.setDonor(user(donorId));item.setAmount(amount);item.setPaymentMethod(method.trim());item.setPaymentReference(reference.trim());return contributionView(contributions.save(item));}
 public Map<String,Object> verifyContribution(Long contributionId,Long adminId,PaymentStatus status){admin(adminId);if(status!=PaymentStatus.VERIFIED&&status!=PaymentStatus.FAILED&&status!=PaymentStatus.REFUNDED)throw new RuntimeException("Invalid payment status");FundContribution item=contributions.findById(contributionId).orElseThrow(()->new ResourceNotFoundException("Contribution not found"));if(item.getPaymentStatus()==PaymentStatus.VERIFIED&&status!=PaymentStatus.REFUNDED)throw new RuntimeException("Verified contributions cannot be changed");if(status==PaymentStatus.VERIFIED&&item.getPaymentStatus()!=PaymentStatus.VERIFIED){FundCampaign c=item.getCampaign();c.setRaisedAmount(c.getRaisedAmount().add(item.getAmount()));campaigns.save(c);}if(status==PaymentStatus.REFUNDED&&item.getPaymentStatus()==PaymentStatus.VERIFIED){FundCampaign c=item.getCampaign();c.setRaisedAmount(c.getRaisedAmount().subtract(item.getAmount()));campaigns.save(c);}item.setPaymentStatus(status);item.setVerifiedBy(user(adminId));item.setVerifiedAt(LocalDateTime.now());return contributionView(contributions.save(item));}
 @Transactional(readOnly=true) public Map<String,Object> receipt(Long contributionId,Long userId){FundContribution item=contributions.findById(contributionId).orElseThrow(()->new ResourceNotFoundException("Contribution not found"));if(!item.getDonor().getId().equals(userId)&&!"ADMIN".equalsIgnoreCase(user(userId).getRole()))throw new RuntimeException("You cannot access this receipt");if(item.getPaymentStatus()!=PaymentStatus.VERIFIED)throw new RuntimeException("A receipt is available after payment verification");return contributionView(item);}
 @Transactional(readOnly=true) public List<Map<String,Object>> monitoring(Long adminId){admin(adminId);return contributions.findAll().stream().map(this::contributionView).toList();}
 private Map<String,Object> campaignView(FundCampaign c){Map<String,Object> m=new LinkedHashMap<>();m.put("id",c.getId());m.put("title",c.getTitle());m.put("category",c.getCategory());m.put("description",c.getDescription());m.put("beneficiary",c.getBeneficiary());m.put("location",c.getLocation());m.put("contactNumber",c.getContactNumber());m.put("goalAmount",c.getGoalAmount());m.put("raisedAmount",c.getRaisedAmount());m.put("status",c.getStatus());m.put("authorId",c.getAuthor().getId());m.put("authorName",c.getAuthor().getName());m.put("createdAt",c.getCreatedAt());m.put("reviewNote",c.getReviewNote());m.put("reactionCount",reactions.countByCampaignId(c.getId()));m.put("comments",comments.findByCampaignIdOrderByCreatedAtAsc(c.getId()).stream().map(this::commentView).toList());m.put("contributions",contributions.findByCampaignIdOrderByCreatedAtDesc(c.getId()).stream().map(this::contributionView).toList());return m;}
 private Map<String,Object> commentView(FundComment c){Map<String,Object>m=new LinkedHashMap<>();m.put("id",c.getId());m.put("authorId",c.getAuthor().getId());m.put("authorName",c.getAuthor().getName());m.put("body",c.getBody());m.put("replyToId",c.getReplyTo()==null?null:c.getReplyTo().getId());m.put("createdAt",c.getCreatedAt());return m;}
 private Map<String,Object> contributionView(FundContribution c){Map<String,Object>m=new LinkedHashMap<>();m.put("id",c.getId());m.put("campaignId",c.getCampaign().getId());m.put("campaignTitle",c.getCampaign().getTitle());m.put("donorId",c.getDonor().getId());m.put("donorName",c.getDonor().getName());m.put("amount",c.getAmount());m.put("paymentMethod",c.getPaymentMethod());m.put("paymentReference",c.getPaymentReference());m.put("paymentStatus",c.getPaymentStatus());m.put("createdAt",c.getCreatedAt());m.put("verifiedAt",c.getVerifiedAt());return m;}
}
